### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Mingdi-W** [liumz93/PEM-Q#6]
Hi, sir!
When I run the example in the PEM-Q/data, I met this issue. Also, when I run my sample, I also met this problem. 
python 3.7.12
######## 06 substitutions... ########
define_substitution.py CC055c 61986726 10 +
[PEM-Q] basename: CC055c
[PEM-Q] cutsite: 61986726
[PEM-Q] cutoff: 10
[PEM-Q] primer_strand: +
Substitutions in cutsite +- cutoff: 0
0
Processing statistics...
Traceback (most recent call last):
  File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 181, in <module>
    main()
  File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 176, in main
    define_substitution(**kwargs)
  File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 126, in define_substitution
    chrom = data["Bait_rname"][0]
  File "/mnt/ZuoStorage3/wumingdi/soft/miniconda/envs/PEM-Q/lib/python3.7/site-packages/pandas/core/series.py", line 939, in __getitem__
    return self._values[key]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by Mingdi-W** [comment]
Also, nothing got in the results folder.

**Comment by liumz93** [comment]
Hi Mingdi-W, if there’s nothing in the results folder, the error likely occurred in the earlier steps. The error you showed me is from step 06, but I believe that’s not the root cause. The IndexError may be due to an improperly generated file. Please check your log file for more details.

**Comment by aprilW0829** [comment]
> Also, nothing got in the results folder.



> Hi, sir! When I run the example in the PEM-Q/data, I met this issue. Also, when I run my sample, I also met this problem. python 3.7.12 ######## 06 substitutions... ######## define_substitution.py CC055c 61986726 10 + [PEM-Q] basename: CC055c [PEM-Q] cutsite: 61986726 [PEM-Q] cutoff: 10 [PEM-Q] primer_strand: + Substitutions in cutsite +- cutoff: 0 0 Processing statistics... Traceback (most recent call last): File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 181, in main() File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 176, in main define_substitution(**kwargs) File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 126, in define_substitution chrom = data["Bait_rname"][0] File "/mnt/ZuoStorage3/wumingdi/soft/miniconda/envs/PEM-Q/lib/python3.7/site-packages/pandas/core/series.py", line 939, in **getitem** return self._values[key] IndexError: index 0 is out of bounds for axis 0 with size 0


I'm having the same issue, but before that I ran the first step I ran the error，[ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False]
Then I'll call pysam in the first few steps. The steps of the AlignmentFile( ) function refer to the post https://github.com/DRL/blobtools/issues/91 have added check_sq=False, so that the first few steps can run normally, but here you encounter the same error, have you solved this problem now, and what is the reason? Thanks.

**Comment by aprilW0829** [comment]
> Hi, sir! When I run the example in the PEM-Q/data, I met this issue. Also, when I run my sample, I also met this problem. python 3.7.12 ######## 06 substitutions... ######## define_substitution.py CC055c 61986726 10 + [PEM-Q] basename: CC055c [PEM-Q] cutsite: 61986726 [PEM-Q] cutoff: 10 [PEM-Q] primer_strand: + Substitutions in cutsite +- cutoff: 0 0 Processing statistics... Traceback (most recent call last): File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 181, in main() File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 176, in main define_substitution(**kwargs) File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 126, in define_substitution chrom = data["Bait_rname"][0] File "/mnt/ZuoStorage3/wumingdi/soft/miniconda/envs/PEM-Q/lib/python3.7/site-packages/pandas/core/series.py", line 939, in **getitem** return self._values[key] IndexError: index 0 is out of bounds for axis 0 with size 0

I'm having the same issue, but before that I ran the first step I ran the error，[ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False]
Then I'll changed the codes in the first few steps of calling AlignmentFile( ) function refer to the post https://github.com/DRL/blobtools/issues/91. I have added check_sq=False, so that the first few steps can run normally, but here  encountered the same error, have you solved this problem now, and what is the reason? Thanks.

**Comment by aprilW0829** [comment]
> Hi, sir! When I run the example in the PEM-Q/data, I met this issue. Also, when I run my sample, I also met this problem. python 3.7.12 ######## 06 substitutions... ######## define_substitution.py CC055c 61986726 10 + [PEM-Q] basename: CC055c [PEM-Q] cutsite: 61986726 [PEM-Q] cutoff: 10 [PEM-Q] primer_strand: + Substitutions in cutsite +- cutoff: 0 0 Processing statistics... Traceback (most recent call last): File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 181, in main() File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 176, in main define_substitution(**kwargs) File "/mnt/ZuoStorage3/wumingdi/soft/PEM-Q/main/define_substitution.py", line 126, in define_substitution chrom = data["Bait_rname"][0] File "/mnt/ZuoStorage3/wumingdi/soft/miniconda/envs/PEM-Q/lib/python3.7/site-packages/pandas/core/series.py", line 939, in **getitem** return self._values[key] IndexError: index 0 is out of bounds for axis 0 with size 0

I'm having the same issue, but before that I ran the first step I ran the error，[ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False]
Then I changed the codes in the first few steps of calling AlignmentFile( ) function refer to the post https://github.com/DRL/blobtools/issues/91. I have added check_sq=False, so that the first few steps can run normally, but here encountered the same error, have you solved this problem now, and what is the reason? Thanks.
